"""empty message

Revision ID: 3316fb3d43a7
Revises: 5ef3653e9030
Create Date: 2019-09-23 08:18:26.508340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3316fb3d43a7'
down_revision = '5ef3653e9030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
