"""followers

Revision ID: 41790714ed88
Revises: 3316fb3d43a7
Create Date: 2019-09-30 23:49:17.871177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41790714ed88'
down_revision = '3316fb3d43a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
